spring:
  jpa:
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create
    properties:
      hiberante:
        format_sql: true
    show_sql: true
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-time: 259200000 # 30 Days-> 259200000 ms
